### PR TITLE
Update systemaliases.als

### PR DESCRIPTION
**Pull request by Serpano**
New HP Status Display with a bar you must put the variable %hstats.new in the translation.dat phrase TurnMessage at the right Position to show the bar

Test it.

Greats Serpano

### CODE REVIEW

**Comment by AndrioCelos** [comment]
Is there a reason you posted five pull requests?
These really should be combined into one or two pull requests.

Having a health bar is nice, but be aware that it won't work with IRC clients that don't render colours. That includes Twitch, and certain mobile clients that I've seen on #BattleArena.

**Comment by Serpano** [comment]
the health bar display only [|||||||||] i want to use a another char but mirc dont use this :(
i use mirc and kiwiirc and at both i can see the bar..

Can you test it ?

**Comment by Serpano** [comment]
and for the 5 requests befor i say and think and write:
this was my first boss i created with the tutorial of the Wiki sry :(
i only want to help :(

**Comment by AndrioCelos** [comment]
@Serpano, in order to create a pull request, you need to [fork](https://help.github.com/articles/fork-a-repo/) the repository, which creates a repository of your own based on it. GitHub already did that for you.

Then you can make and commit changes to a certain (single) [branch](https://help.github.com/articles/about-branches/) in your own repository, then submit a [pull request](https://help.github.com/articles/using-pull-requests/) from there. That way, all your proposed changes are combined into a single pull request. You can even amend it by pushing further commits while the request is open.

If you use a [standalone Git client](https://help.github.com/articles/set-up-git/), you can change more than one file with a single commit, which is usually what you want.

We don't mean to attack you or undermine your efforts to contribute, but I'm afraid not every change would necessarily work out.

(I said earlier that your health bar could cause issues with clients that don't render colours, but that doesn't mean that we couldn't combine both displays, perhaps with a config option to revert back to just the descriptive one.)

**Comment by Serpano** [comment]
Thank you :)

**Comment by Iyouboushi** [comment]
I will probably add the healthbar idea to the bot but not as it currently stands in this file.   I'll need to add a system flag that can be toggled, and probably move the healthbar generation to its own alias to make it easier to edit/adjust.  

It might be a few days before I get it done though.

**Pull request closed without merging**
