### PR TITLE
Update techniques.db and weapons.db

### PR DESCRIPTION
**Pull request by Serpano**
[SoulEather.zip](https://github.com/Iyouboushi/mIRC-BattleArena/files/409644/SoulEather.zip)
Here are a new scythe from the Anime SoulEater
you can add this if you want...

I use Github for my first time and i dont know how i can edit more files at the same time :/

### CODE REVIEW

**Comment by Iyouboushi** [comment]
The weapon is too OP for the main game.  Plus there are some issues with the files.

If you want to keep this weapon in your own copy that's fine but it isn't suited for the main game.

**Comment by Serpano** [comment]
hmm to op ? sure if you know the anime than you understand why SoulEater is the Greatest Scythe :)

When you activates seelenresonanz the enemy has no chance to defeat this person who holding this Scythe :)

**Comment by Tiranadel** [comment]
Then the problem would be that would be the only weapon people would use. Really don't need another OP weapon when I'm sure there's already enough OP weapons in the bot.

**Comment by Serpano** [comment]
sure many weapons are op to also why not adding SoulEater ?

**Pull request closed without merging**
