### PR TITLE
Create beerus_clone.char

### PR DESCRIPTION
**Pull request by Serpano**
the last file for the boss Beerus...
Please be sure you have the following changes: The Weapon Berusclaw , The Techniques for the Weapon, The Bossfile Beerus.char and the monster Summonfile beerus_clone.char

You can Add this epic boss :)

### CODE REVIEW

**Comment by Iyouboushi** [comment]
Closing all these pull requests.

First, all of these could have just been done with one request rather than four.  Second, you're trying to implement a "god" but the file is a level 1 scrub that one could sneeze on and kill.   Third, Smz is already working on a better version of this boss and it will be implemented when he's finished.

**Comment by Serpano** [comment]
hmm this whas my first boss i created with the tutorial of the Wiki sry :(
i only want to help :(

**Comment by AndrioCelos** [comment]
@Iyouboushi is right, but I should point out that the absolute values of the attributes don't seem to make much difference at this point, because of the level sync mechanic.

**Comment by Tiranadel** [comment]
To comment further, 100% counter might be a little crazy on any level. Probably more on level 10 for the new players, but will also have to consider higher levels and the chance he shows up in Torment battles.

**Pull request closed without merging**
